### ISSUE TITLE
Post different app review to different channels?

### ISSUE THREAD

**Issue by Vortec4800** [TradeMe/ReviewMe#12]
Is it possible to have the bot monitoring several apps, and post them to project-specific channels, without having to spin up multiple instances of the bot? Perhaps we could just specify a custom hook per app, otherwise it uses the default hook?

**Comment by athornz** [comment]
Great suggestion. Slack webhooks allow a channel other than the default to be specified in the JSON payload, so I think that would be the best approach.

It should be quite straightforward to implement.

**Comment by Vortec4800** [comment]
I'm pretty new to Slack app development so you'll have to forgive me for my lack of understanding.

I've noticed the values I put in for the chat bot name, icon and emoji are ignored - the Slack App values are used instead, and the channel always points to the one that was specified when creating the hook.

Is it possible to create a hook that can post to any channel, so the same hook is always used but a custom channel is specified? Or do you need a separate hook for every channel?

**Comment by athornz** [comment]
It's possible to override the default channel. I just took a quick look into the code and ReviewMe already supports overriding the channel, but it doesn't actually seem to be working (Manually posting to the slack hook does).

**Comment by athornz** [comment]
Actually, I was setting the channel on the wrong app 😄

Specifying a channel in the app configuration does work:

`
{
      "appId": "1234",
      "channel":"#builds"
}
`

Also tested working:
- botUsername
- botEmoji

botIcon isn't working - I'll open a PR to fix this soon.

So your issue might be something different - let me know if you can't get the channel working.

**Comment by Vortec4800** [comment]
I haven't actually tried the custom channel setting, just noticed that botUsername and botEmoji wasn't working and didn't see the custom channel setting in the README.

I'll test it and take screenshots and upload on Monday morning to a new issue so we can keep them separate, sounds like they may be separate problems.

**Comment by athornz** [comment]
I've just published 1.0.7, which fixes the bot icon parameter not working. 

All other parameters are working afaik so let me know if there are any more issues.

I'll close this issue for now.
