### ISSUE TITLE
Bot Keys not working

### ISSUE THREAD

**Issue by Vortec4800** [TradeMe/ReviewMe#15]
I've got some information about some of these keys not working. I'm setting both of these as follows in my config file:

```
  "botUsername": "Review Bot",
  "botEmoji": ":star:",
```

However when the message to Slack posts, it looks like this:

![screen shot 2018-08-06 at 9 13 19 am](https://user-images.githubusercontent.com/396122/43721645-fe85fcd4-9958-11e8-8117-2ea97846a36f.png)

What else can I provide to help debug?

**Comment by Vortec4800** [comment]
I think I may have found the issue. It seems like this is no longer supported when you create a Slack App:

> The majority of your legacy code for sending messages using incoming Webhooks should continue to work within a Slack app without much modification; the only thing you can no longer do is customize the destination channel and author identity at runtime.

https://api.slack.com/custom-integrations/incoming-webhooks

**Comment by athornz** [comment]
ah, that's a pain. I guess we'll need to add that information to the readme.
