### ISSUE TITLE
Running ReviewMe in another Node app

### ISSUE THREAD

**Issue by Vortec4800** [TradeMe/ReviewMe#16]
I've got a Node server already set up and running other functions on my server. Is there a way to require and run this from within this existing node server instead of running it as a standalone program?

Something like

     const reviewMe = require('reviewMe');
     reviewMe.start({config: values});

**Comment by athornz** [comment]
Yes absolutely. ReviewMe is a just a package like any other - it needs to be started from somewhere, but that doesn't need to be a standalone app.

I have an app that runs ReviewMe with the following code:

`
var reviewme = require("@trademe/reviewme");
var config = require("./config.json");

reviewme.start(config);
`

You could put this in your existing app no problem.

**Comment by Vortec4800** [comment]
Awesome, thanks for the info. I figured this was possible but my Node knowledge is still under development so I wasn't sure if there were details I was missing to make it work.
