### ISSUE TITLE
Google play scraping is breaking Android reviews

### ISSUE THREAD

**Issue by jamiesanson** [TradeMe/ReviewMe#2]
The current version of the Google Play Scraper dependency is encountering some issues when scraping information from the play store, specifically this issue: https://github.com/facundoolano/google-play-scraper/issues/192

A quick fix could be updating the dependency to `v6.0.0`, however as the scaper is only used for app name and icon perhaps this dependency could be removed in favour of serving a local image and app name from some form of configuration

**Comment by athornz** [comment]
A quick fix for now is probably the easiest - using the scraper means less maintenance of a users ReviewMe config as well.
