### ISSUE TITLE
error code ENOENT no such file or directory, chmod

### ISSUE THREAD

**Issue by CyrilNb** [TradeMe/ReviewMe#28]
Hi, when I run `npm install -g @trademe/reviewme` I got stuck with this error.

> npm ERR! path /usr/local/lib/node_modules/@trademe/reviewme/bin/reviewme.js
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! syscall chmod
> npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/@trademe/reviewme/bin/reviewme.js'
> npm ERR! enoent This is related to npm not being able to find a file.

I've been trying since hours to fix it.
Can I have some help please ? Does it come from my configuration ? (I'm on macOS, node version: v11.9.0)

Thanks!

**Comment by harpo** [comment]
Same problem for me. I am on Ubuntu 16.04 with node version 8.15.0.

**Comment by jamiesanson** [comment]
This should have been addressed in 2.0.0.
