### ISSUE TITLE
cannot read property 'client_id' of undefined

### ISSUE THREAD

**Issue by scouech** [TradeMe/ReviewMe#44]
Hi, just tried to run this today. It works for app store, however for the play store I get this (see screenshot). Do you know why? Cheers

<img width="1645" alt="Screenshot 2020-07-02 at 5 25 55 PM" src="https://user-images.githubusercontent.com/26603052/86377830-237a9900-bc89-11ea-9d6a-ef93c229a9cd.png">

**Comment by athornz** [comment]
Are you sure that the googleapikey.json file exists, and the path is correct?

**Comment by scouech** [comment]
Yep you are right! Add to modify the file path in the config file to ../filename instead of ~/filename ☺️ Cheers
